### ISSUE TITLE
[feature request] Add shortcut to create new windows

### ISSUE THREAD

**Issue by anddam** [sobitcorp/metapad#9]
Please add a `File > New window` menu item with shortcut (likely ctrl-shift-N) to create a new empty window.

The only way I could find now to jot something on the fly is launching a new instance from the windows menu.

**Comment by sobitcorp** [comment]
You're looking for `File > Launch > New window (Ctrl+I)`. This existed way back pre-v1.5. I would actually prefer it to be `Ctrl+Shift+N` myself. So what does the community think?
1. Change `Ctrl+I -> Ctrl+Shift+N`
2. Make both open new window (make `Ctrl+Shift+N` an alias for `Ctrl+I`)
3. Don't touch

**Comment by Gitoffthelawn** [comment]
I think, at least for now, there is little harm in making both `Ctrl+I` and `Ctrl+Shift+N` open a new window.

Ideally, the user could set all keyboard shortcuts via `metapad.ini` (perhaps even having one or more optional aliases for each shortcut).

**Comment by anddam** [comment]
I'd rather keep a single shortcut and make it configurable.

I am closing this but I wonder why this was under `Launch` submenu, or why the latter exist at all, I'd flatten the `File` menu altogheter, the `Edit` menu has way more elements anyway.

**Comment by sobitcorp** [comment]
That's a question for Alex (the original metapad dev). I'm just trying to keep metapad as true to original as possible :)
